### ISSUE TITLE
[Bug]: LightVirtualFile issue

### ISSUE THREAD

**Issue by apihug** [apihug/apihug-ide-plugin#1]
### Checklist

- [X] I have updated the ApiHug plugin to the **latest version**
- [X] I have updated the ApiHug SDK to the **latest version**
- [X] I followed the [handbook](https://github.com/apihug/apihug.com/tree/master/docs/handbook) and the [features](https://github.com/apihug/apihug.com/tree/master/docs/IDE) introduction and I double checked my configuration.
- [X] I have check [FAQ](https://github.com/apihug/apihug.com/blob/master/docs/IDE/999_FAQ.md) and I did not find the answer.
- [X] I have searched closed issue and I did not find the answer.

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA version

2023.2.3

### Plugin version

0.2.1

### Describe the bug

when open a ApiHug project,  after the project loaded, a error warning showing up, but the project **load and build successfully**. 

for light Virtual File should add this logic:

```java
if (virtualFile instanceof LightVirtualFile) return;
```

### Error log

```
java.lang.Throwable: Light files should have PSI only in one project, existing=com.intellij.psi.SingleRootFileViewProvider{vFile=LightVirtualFile: \api.proto, content=VirtualFileContent{size=1435}, eventSystemEnabled=false} in Project(name=dalong, containerState=COMPONENT_CREATED, componentStore=D:\Aaron\workspace\projects\ai\dalong), requested in Project(name=we-hope-assistant, containerState=COMPONENT_CREATED, componentStore=D:\Aaron\workspace\projects\idea\apihug-assistant); psiFiles: class com.intellij.protobuf.lang.psi.impl.PbFileImpl [Language: protobuf]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.checkLightFileHasNoOtherPsi(FileManagerImpl.java:205)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:193)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:358)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:156)
	at com.apihug.assistant.plugin.l.e$b.a(SourceFile:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.apihug.assistant.plugin.l.e$b.a(SourceFile:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by apihug** [comment]
after   `0.2.9`+  catch this exception and ignore it avoid this noisy,  as this happen during editing the broken of the AST syntax.

**Comment by apihug** [comment]
close
